environment: "local"
server:
  address: "localhost:5001"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: "5432"
  db_name: "go_forms"
  user: "developer"
jwt:
  access_ttl: 180
  refresh_ttl: 1800
  audience: "github.com/banderveloper/go-forms-web"
  issuer: "github.com/banderveloper/go-forms"

