environment: "local"
server:
  address: "localhost:5001"
  timeout: 4s
  idle_timeout: 60s
database:
  host: "localhost"
  port: "5432"
  db_name: "go_forms"
  user: "developer"
  password: "secret"
jwt:
  key: "temporarysecretjwtkeyasdasdasdasdasd"
  access_token_ttl: 180
  refresh_token_ttl: 180
